### ISSUE TITLE
can you pulish more documents on how to make a addin package ?

### ISSUE THREAD

**Issue by yanzixiang** [RV1989/Tia-Portal-Base-AddIn#1]
can you pulish more documents on how to make a addin package ?
have siemens published it ?

**Comment by RV1989** [comment]
do you mean creating the .add-in from the .dll?
you can find the command used in the post build configuration. This is also explained in the help of Tia portal V16 under 
Creating an add-in from the DLL

**Comment by yanzixiang** [comment]
> do you mean creating the .add-in from the .dll?
> you can find the command used in the post build configuration. This is also explained in the help of Tia portal V16 under
> Creating an add-in from the DLL

thanks,I just installed V16,and saw it.
