### ISSUE TITLE
hi,do you know how to enable the addin ?

### ISSUE THREAD

**Issue by yanzixiang** [RV1989/Tia-Portal-Base-AddIn#2]
i got this,
and can not enable it.
plz help.

![YZX Tia Addin CanNOTSelect](https://user-images.githubusercontent.com/33214/85949292-7fdb7100-b988-11ea-926c-706ebc091f2c.PNG)

**Comment by RV1989** [comment]
I have no idea. Does it show an error of some sort because of the red x before the add in. Did you compile the add-in with the publisher?

**Comment by yanzixiang** [comment]
I have no idea. Does it show an error of some sort because of the red x before the add in.
no,there is NOTHING there.

@Did you compile the add-in with the publisher?
YES.

**Comment by mg-0815** [comment]
Hello yanzixiang

I have the same problem and no solution.
What was your problem?
I hope you can help me

Thank you

Mario

**Comment by mg-0815** [comment]
Problem is solved

ONLY FOR INFORMATION:
My Problem happened because I wanted to have a connection to the G120X.
For this you need to install "**Startdrive_Advanced_V17_SP1.iso**" too

Mario
